//-------------------------------------------------
// autogenerated by com.zotoh.dbio.codegen
//
// ${gendate}
//-------------------------------------------------

package ${pkg}

import com.zotoh.dbio.core.AbstractModel
import com.zotoh.dbio.meta._
import com.zotoh.dbio.core.SQLProc
import java.util.{Calendar,Date}
import java.sql.{Time,Timestamp}
import java.math.{BigDecimal,BigInteger}


class ${classname} extends AbstractModel with ${trait} {

${classbody}


}

