/*??
 * COPYRIGHT (C) 2012-2013 CHERIMOIA LLC. ALL RIGHTS RESERVED.
 *
 * THIS IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR
 * MODIFY IT UNDER THE TERMS OF THE APACHE LICENSE,
 * VERSION 2.0 (THE "LICENSE").
 *
 * THIS LIBRARY IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
 * BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
 *
 * SEE THE LICENSE FOR THE SPECIFIC LANGUAGE GOVERNING PERMISSIONS
 * AND LIMITATIONS UNDER THE LICENSE.
 *
 * You should have received a copy of the Apache License
 * along with this distribution; if not, you may obtain a copy of the
 * License at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 ??*/


package com.zotoh.blason
package io

import java.io.File

import com.zotoh.frwk.util.StrUtils.nsb
import FILEAction._

/**
 * An Event generated by the FilePicker device.  This event carries the
 * reference to the file which has been picked up by the device.
 *
 * @author kenl
 */
@SerialVersionUID(4177245480806752339L)
class FILEEvent(src:EventEmitter, private var _file:File) extends AbstractEvent(src) {

  private var _action:FILEAction=null
  private var _origPath=""

  /**
   * @param dev
   * @param originalFile
   * @param f
   * @param e
   */
  def this(src:EventEmitter, originalFile:String, f:File, act:FILEAction) {
    this(src,f)
    _origPath=nsb(originalFile)
    _action=act
  }

  def action() = _action

  /**
   * @return
   */
  def origFilePath() = _origPath

  /**
   * @return
   */
  def file() = _file

}

