/*??
 * COPYRIGHT (C) 2012 CHERIMOIA LLC. ALL RIGHTS RESERVED.
 *
 * THIS IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR
 * MODIFY IT UNDER THE TERMS OF THE APACHE LICENSE, 
 * VERSION 2.0 (THE "LICENSE").
 *
 * THIS LIBRARY IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
 * BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
 *   
 * SEE THE LICENSE FOR THE SPECIFIC LANGUAGE GOVERNING PERMISSIONS 
 * AND LIMITATIONS UNDER THE LICENSE.
 *
 * You should have received a copy of the Apache License
 * along with this distribution; if not, you may obtain a copy of the 
 * License at 
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 ??*/

package com.zotoh.blason
package io

import org.apache.commons.io.{IOUtils=>IOU}
import com.zotoh.frwk.util.StrUtils._
import com.zotoh.frwk.net.NetUtils._

import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.net.Socket
import java.net.SocketException


/**
 * Events generated by a TCP device.
 *
 * @author kenl
 */
@SerialVersionUID(-3310871938767923755L)
class SocketEvent(src:EventEmitter,
  private var _soc:Socket) extends AbstractEvent(src) {

  protected def setSocketTimeout(millis:Int) {
    _soc.setSoTimeout(millis)
  }

  def getSockOut() = {
    if (_soc==null) null else _soc.getOutputStream()
  }

  def getSockIn() = {
    if (_soc==null) null else _soc.getInputStream()
  }

  override def destroy() {
    IOU.closeQuietly(_soc)
    _soc=null
  }

}
